const CHANGE_PRESENTATION_TITLE = 'CHANGE_PRESENTATION_TITLE'
const IMPORT_PRESENTATION = 'IMPORT_PRESENTATION'

const ADD_SLIDE = 'ADD_SLIDE'
const CREATE_SLIDE = 'CREATE_SLIDE'
const SELECT_SLIDE = 'SELECT_SLIDE'
const SET_BACKGROUND_SLIDE = 'SET_BACKGROUND_SLIDE'
const MOVE_SLIDE = 'MOVE_SLIDE'
const DELETE_SLIDE = 'DELETE_SLIDE'

const UPDATE_SLIDE = 'UPDATE_SLIDE'

const UPDATE_PAGE = 'UPDATE_PAGE'

const SELECT_OBJECT = 'SELECT_OBJECT'
const DELETE_OBJECT = 'DELETE_OBJECT'
const RESIZE_OBJECT = 'RESIZE_OBJECT'
const MOVE_OBJECT = 'MOVE_OBJECT'

const CREATE_PRIMITIVE = 'CREATE_PRIMITIVE_RECTANGLE'
const SET_COLOR_PRIMITIVE = 'SET_COLOR_PRIMITIVE'
const SET_STROKECOLOR_FIGURE = 'SET_STROKECOLOR_RECTANGLE'

const CREATE_IMAGE = 'CREATE_IMAGE'
const CREATE_TEXTBOX = 'CREATE_TEXTBOX'
const SET_TEXT = 'SET_TEXT'
const CHANGE_TEXT_COLOR = 'CHANGE_TEXT_COLOR'
const CHANGE_TEXT_SIZE = 'CHANGE_TEXT_SIZE'
const CHANGE_FONT = 'CHANGE_FONT'
const CHANGE_TEXT_STYLE = 'CHANGE_TEXT_STYLE'

export {
  IMPORT_PRESENTATION,
  CHANGE_PRESENTATION_TITLE,
  ADD_SLIDE,
  CREATE_SLIDE,
  SELECT_SLIDE,
  SET_BACKGROUND_SLIDE,
  MOVE_SLIDE,
  DELETE_SLIDE,
  SELECT_OBJECT,
  DELETE_OBJECT,
  RESIZE_OBJECT,
  MOVE_OBJECT,
  SET_COLOR_PRIMITIVE,
  CREATE_PRIMITIVE,
  SET_STROKECOLOR_FIGURE,
  CREATE_IMAGE,
  CREATE_TEXTBOX,
  SET_TEXT,
  CHANGE_TEXT_COLOR,
  CHANGE_TEXT_SIZE,
  CHANGE_FONT,
  CHANGE_TEXT_STYLE,
  UPDATE_SLIDE,
  UPDATE_PAGE,
}
