const CHANGE_PRESENTATION_TITLE = 'CHANGE_PRESENTATION_TITLE'

const ADD_SLIDE = 'ADD_SLIDE'
const SELECT_SLIDE = 'SELECT_SLIDE'
const DELETE_SLIDE = 'DELETE_SLIDE'
const UPDATE_SLIDE = 'UPDATE_SLIDE'
const CHANGE_SLIDE_COLOR = 'CHANGE_SLIDE_COLOR'

const UPDATE_PAGE = 'UPDATE_PAGE'

const SELECT_OBJECT = 'SELECT_OBJECT'
const REMOVE_OBJECT = 'REMOVE_OBJECT'
const ADD_TEXT = 'ADD_TEXT'
const ADD_TRIANGLE = 'ADD_TRIANGLE'
const ADD_RECTANGLE = 'ADD_RECTANGLE'
const ADD_CIRCLE = 'ADD_CIRCLE'
const ADD_IMAGE = 'ADD_IMAGE'
const ADD_BACK_IMAGE = 'ADD_BACK_IMAGE'

const CHANGE_ELEMENT_COLOR = 'CHANGE_ELEMENT_COLOR'
const CHANGE_SHAPE_STROKE_WIDTH = 'CHANGE_SHAPE_STROKE_WIDTH'
const CHANGE_SHAPE_STROKE_COLOR = 'CHANGE_SHAPE_STROKE_COLOR'

const BOLD_TEXT = 'BOLD_TEXT'
const ITALIC_TEXT = 'ITALIC_TEXT'
const UNDERLINE_TEXT = 'UNDERLINE_TEXT'
const CHANGE_FONT = 'CHANGE_FONT'
const CHANGE_TEXT_ALIGN_LEFT = 'CHANGE_TEXT_ALIGN_LEFT'
const CHANGE_TEXT_ALIGN_CENTER = 'CHANGE_TEXT_ALIGN_CENTER'
const CHANGE_TEXT_ALIGN_RIGHT = 'CHANGE_TEXT_ALIGN_RIGHT'

const ADD_FONT_SIZE = 'ADD_FONT_SIZE'
const SUB_FONT_SIZE = 'SUB_FONT_SIZE'

const UPDATE_RECT = 'UPDATE_RECT'

const GO_TO_LAST_STATE = 'BACK_TO_LAST_STATE'

const GO_TO_NEXT_STATE = 'GO_TO_NEXT_STATE'

export {
  CHANGE_PRESENTATION_TITLE,
  ADD_SLIDE,
  SELECT_SLIDE,
  DELETE_SLIDE,
  SELECT_OBJECT,
  REMOVE_OBJECT,
  UPDATE_SLIDE,
  CHANGE_SLIDE_COLOR,
  UPDATE_PAGE,
  ADD_TEXT,
  ADD_TRIANGLE,
  ADD_RECTANGLE,
  ADD_CIRCLE,
  ADD_IMAGE,
  ADD_BACK_IMAGE,
  CHANGE_ELEMENT_COLOR,
  CHANGE_SHAPE_STROKE_WIDTH,
  CHANGE_SHAPE_STROKE_COLOR,
  BOLD_TEXT,
  ITALIC_TEXT,
  UNDERLINE_TEXT,
  CHANGE_FONT,
  CHANGE_TEXT_ALIGN_LEFT,
  CHANGE_TEXT_ALIGN_CENTER,
  CHANGE_TEXT_ALIGN_RIGHT,
  ADD_FONT_SIZE,
  SUB_FONT_SIZE,
  UPDATE_RECT,
  GO_TO_LAST_STATE,
  GO_TO_NEXT_STATE,
}
